// Generated by CoffeeScript 1.3.3
(function() {
  var Cat, Kitten, db, findKitty, mongoose, respond, restify, schema, server;

  restify = require('restify');

  mongoose = require('mongoose');

  server = restify.createServer();

  db = mongoose.createConnection('localhost', 'mongoose');

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log("hell yes");
  });

  schema = mongoose.Schema({
    name: 'string'
  });

  Cat = db.model('Cat', schema);

  Kitten = db.model('Kitten', schema);

  respond = function(req, res, next) {
    var kitten, kitty;
    res.send("hello " + req.params.name);
    console.log("test");
    kitty = new Cat({
      name: 'Nyan'
    });
    kitten = new Kitten({
      name: 'wtfman'
    });
    kitten.save(function(err) {
      return console.log("saved kitten");
    });
    kitty.save(function(err) {
      if (err) {
        return console.log("error");
      } else {
        return console.log("saved");
      }
    });
    return console.log(kitty.name);
  };

  /*
  Kitten.find(function (err, kittens) {
    if (err) /
    console.log(kittens)
  })
  */


  findKitty = function(req, res, next) {
    Cat.find(function(err, cats) {
      return console.log(cats);
    });
    return res.end("end");
  };

  server.get('/hello/:name', respond);

  server.get('/kitty/', findKitty);

  server.listen(8080, function() {
    return console.log("listening to server " + server.name + ", " + server.url);
  });

}).call(this);
