// Generated by CoffeeScript 1.3.3
(function() {
  var Project, connection, mongoose,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  mongoose = require('mongoose');

  connection = require('../utils/DBConnection.js');

  Project = (function() {

    function Project(name, project, Project) {
      var db, projectName, schema;
      this.name = name;
      this.project = project;
      this.Project = Project;
      this.getProjectList = __bind(this.getProjectList, this);

      this.save = __bind(this.save, this);

      db = connection.createMongoDBConnection();
      schema = mongoose.Schema({
        name: 'string'
      });
      this.Project = db.model("Project", schema);
      projectName = this.name;
      console.log("this is project name " + this.name + " and this is project name " + projectName);
      this.project = new this.Project({
        name: projectName
      });
    }

    Project.prototype.save = function(res) {
      var _this = this;
      return this.project.save(function(err) {
        if (err) {
          console.log("error saving project");
          res.contentType = 'json';
          res.code = 404;
          return res.send({
            error: 'erorr saving project'
          });
        } else {
          console.log("saved project");
          res.contentType = 'json';
          res.code = 200;
          return res.send({
            success: "" + _this.name + " has been saved"
          });
        }
      });
    };

    Project.prototype.getProjectList = function(res) {
      var _this = this;
      return this.Project.find(function(err, projects) {
        res.contentType = 'json';
        res.code = 200;
        return res.send(projects);
      });
    };

    return Project;

  })();

  module.exports.Project = Project;

}).call(this);
