// Generated by CoffeeScript 1.3.3
(function() {
  var mongoose;

  mongoose = require('mongoose');

  exports.createMongoDBConnection = function() {
    var db;
    db = mongoose.createConnection('localhost', 'TeamCollaboration');
    db.on('error', console.error.bind(console, 'connection error:'));
    db.once('open', function() {
      return console.log("Connection Establish");
    });
    return db;
  };

}).call(this);
