// Generated by CoffeeScript 1.3.3
(function() {

  TeamCollaboration.AdminMain = Backbone.View.extend({
    template: _.template($('#tpl-admin-main').html()),
    render: function(e) {
      this.$el.html(this.template());
      return this;
    }
  });

  TeamCollaboration.AdminSideBar = Backbone.View.extend({
    template: _.template($('#tpl-admin-sidebar').html()),
    render: function(e) {
      return this.template();
    }
  });

  TeamCollaboration.AdminProjectManagementMain = Backbone.View.extend({
    events: {
      "click button": "createProject"
    },
    template: _.template($('#tpl-admin-project-management-main').html()),
    createProject: function() {
      var projectName;
      projectName = $('#projectName').val();
      this.model = new TeamCollaboration.ProjectModel();
      this.model.set({
        name: projectName
      });
      this.model.save();
      this.collection.add(this.model);
      return $('#projectName').val("");
    },
    render: function(e) {
      this.$el.html(this.template());
      return this;
    }
  });

  TeamCollaboration.AdminProjectListView = Backbone.View.extend({
    template: _.template($('#tpl-admin-project-management-sidebar').html()),
    initialize: function() {
      this.$el.append(this.template());
      this.collection.on("reset", this.render, this);
      return this.collection.on("add", this.addProject, this);
    },
    addProject: function(project) {
      this.projectView = new TeamCollaboration.AdminProjectView({
        model: project
      });
      return this.$el.append(this.projectView.render());
    },
    render: function() {
      this.collection.forEach(this.addProject, this);
      return this;
    }
  });

  TeamCollaboration.AdminProjectView = Backbone.View.extend({
    template: _.template($('#tpl-project').html()),
    render: function(e) {
      console.log(this.model);
      return this.template(this.model.toJSON());
    }
  });

}).call(this);
