// Generated by CoffeeScript 1.3.3
(function() {

  TeamCollaboration.ApplicationView = Backbone.View.extend({
    template: _.template($('#tpl-frontpage-sidebar').html()),
    render: function(e) {
      return this.template();
    }
  });

}).call(this);
