// Generated by CoffeeScript 1.3.3
(function() {

  TeamCollaboration.ApplicationSideBarView = Backbone.View.extend({
    el: $('#sidebar'),
    template: _.template($('#tpl-frontpage-sidebar').html()),
    render: function(e) {
      return this.$el.html(this.template());
    }
  });

}).call(this);
