// Generated by CoffeeScript 1.3.3
(function() {

  TeamCollaboration.ApplicationView = Backbone.View.extend({
    template: _.template($('#tpl-frontpage-sidebar').html()),
    render: function(e) {
      this.$el.html(this.template());
      return this;
    }
  });

}).call(this);
